# Generated by Django 3.0.3 on 2020-03-28 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Puzzle')),
                ('theme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Theme')),
            ],
        ),
    ]
