# Generated by Django 3.0.3 on 2020-03-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_puzzletheme_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzletheme',
            old_name='puzzle_id',
            new_name='puzzle',
        ),
        migrations.RenameField(
            model_name='puzzletheme',
            old_name='theme_id',
            new_name='theme',
        ),
    ]
