# Generated by Django 3.0.3 on 2020-03-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200328_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='themes',
            field=models.ManyToManyField(to='inventory.Theme'),
        ),
    ]
